import "./globals.css";
import { Bodoni_Moda, Montserrat } from "next/font/google";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";

import AllProviders from "@/components/layout/AllProviders";
import NavBar from "@/components/layout/header/NavBar";
import SidebarCart from "@/components/cart/SidebarCart";
import Footer from "@/components/layout/footer/Footer";
import { SidebarInset } from "@/components/ui/sidebar";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700"],
});

const bodoniModa = Bodoni_Moda({
  subsets: ["latin"],
  variable: "--font-bodoni-moda",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Zal Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        montserrat.variable,
        bodoniModa.variable,
        "font-sans",
      )}>
      <body>
        <AllProviders>
          <SidebarInset>
            <NavBar />
            {children}
            <Footer />
          </SidebarInset>
          <SidebarCart />
          <ReactQueryDevtools />
        </AllProviders>
      </body>
    </html>
  );
}
