import type { Metadata } from "next";
import { Bodoni_Moda, Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/header/theme-provider";
import NavBar from "@/components/header/NavBar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import SidebarCart from "@/components/cart/SidebarCart";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700"],
});

const bodoniModa = Bodoni_Moda({
  subsets: ["latin"],
  variable: "--font-bodoni-moda",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Zal Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        montserrat.variable,
        bodoniModa.variable,
        "font-sans",
      )}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <SidebarProvider
            defaultOpen={false}
            style={
              {
                "--sidebar-width": "30rem",
                "--sidebar-width-mobile": "20rem",
              } as React.CSSProperties
            }>
            <SidebarInset>
              <NavBar />
              {children}
            </SidebarInset>
            <SidebarCart />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
